#ifndef OPTIONS_H
# define OPTIONS_H

# define WINDOW_WIDTH			720
# define WINDOW_HEIGHT			480

# define SAMPLES				100
# define PATH_DEPTH				8
# define RUSSIAN_DEPTH			4
# define UPLOAD_INTERVAL		3
# define FOCUS_EFFECT			0
# define DEFAULT_ALBEDO			0.18

# define QUIT_AFTER_SAMPLING	0

# define INTERSECTION_MIN		0.001f
# define INTERSECTION_MAX		INFINITY

# define SHAPE_DATA_CAPACITY	64
# define SHAPE_ID_SPHERE		0
# define SHAPE_ID_PLANE			1

# define SCENE_SHAPES_CAPACITY	16
# define SCENE_LIGHTS_CAPACITY	8

# define SAMPLING_COSINE_PBRT
//# define SAMPLING_UNIFORM

#endif
