#ifndef PARAMETERS_H
# define PARAMETERS_H

# define WINDOW_WIDTH			720
# define WINDOW_HEIGHT			480

# define SAMPLES				200
# define PATH_DEPTH				5
# define RUSSIAN_DEPTH			2
# define UPLOAD_INTERVAL		4

# define QUIT_AFTER_SAMPLING	0

# define INTERSECTION_MIN		0.001f
# define INTERSECTION_MAX		INFINITY

# define SHAPE_DATA_CAPACITY	64
# define SHAPE_ID_SPHERE		0
# define SHAPE_ID_PLANE			1

# define SCENE_SHAPES_CAPACITY	16
# define SCENE_LIGHTS_CAPACITY	8

#endif
