#ifndef PARAMETERS_H
# define PARAMETERS_H

# define WINDOW_WIDTH			720
# define WINDOW_HEIGHT			480

# define SAMPLES				500
# define PATH_DEPTH				1

# define INTERSECTION_MIN		0.0001f
# define INTERSECTION_MAX		INFINITY

# define SHAPE_DATA_CAPACITY	64
# define SHAPE_ID_SPHERE		0
# define SHAPE_ID_PLANE			1

# define SCENE_SHAPES_CAPACITY	16
# define SCENE_LIGHTS_CAPACITY	8

#endif
