#ifndef CL_SOURCES_H
# define CL_SOURCES_H

# define RT_CL_FLAGS							"-I ./parameters/"
# define RT_CL_MAIN_FUNCTION					"cl_main"

# define RT_SOURCE_CL_FOLDER					"./cl_renderer/cl_source/"
# define RT_SOURCE_CL_F4						"cl_f4"
# define RT_SOURCE_CL_SETTINGS					"cl_settings"
# define RT_SOURCE_CL_RANDOM					"cl_random"
# define RT_SOURCE_CL_RAY						"cl_ray"
# define RT_SOURCE_CL_COLOR						"cl_color"
# define RT_SOURCE_CL_MATERIAL					"cl_material"
# define RT_SOURCE_CL_INTERSECTION_X			"cl_intersection_x"
# define RT_SOURCE_CL_OBJECT					"cl_object"
# define RT_SOURCE_CL_OBJECT_SPHERE				"cl_object_sphere"
# define RT_SOURCE_CL_OBJECT_PLANE				"cl_object_plane"
# define RT_SOURCE_CL_OBJECT_CONE				"cl_object_cone"
# define RT_SOURCE_CL_OBJECT_CYLINDER			"cl_object_cylinder"
# define RT_SOURCE_CL_OBJECT_BOX				"cl_object_box"
# define RT_SOURCE_CL_OBJECT_PARABOLOID			"cl_object_paraboloid"
# define RT_SOURCE_CL_OBJECT_MOEBIUS			"cl_object_moebius"
# define RT_SOURCE_CL_OBJECT_LIMITED			"cl_object_limited"
# define RT_SOURCE_CL_OBJECT_TORUS				"cl_object_torus"
# define RT_SOURCE_CL_OBJECT_JULIA				"cl_object_julia"
# define RT_SOURCE_CL_OBJECT_MANDELBULB			"cl_object_mandelbulb"
# define RT_SOURCE_CL_OBJECT_PERFORATED_CUBE	"cl_object_perforated_cube"
# define RT_SOURCE_CL_OBJECT_CSG				"cl_object_csg"
# define RT_SOURCE_CL_OBJECT_EXPLOSION			"cl_object_explosion"
# define RT_SOURCE_CL_OBJECT_X					"cl_object_x"
# define RT_SOURCE_CL_OBJECT_NORMAL				"cl_object_normal"
# define RT_SOURCE_CL_SCENE_X					"cl_scene_x"
# define RT_SOURCE_CL_TEXTURE					"cl_texture"
# define RT_SOURCE_CL_SAMPLE_X					"cl_sample_x"
# define RT_SOURCE_CL_LIGHT_BASIC				"cl_light_basic"
# define RT_SOURCE_CL_LIGHT_AREA				"cl_light_area"
# define RT_SOURCE_CL_RADIANCE_X				"cl_radiance_x"
# define RT_SOURCE_CL_FILTER					"cl_filter_x"
# define RT_SOURCE_CL_CAMERA					"cl_camera"
# define RT_SOURCE_CL_CAMERA_DEFINITION			"cl_camera_definition"
# define RT_SOURCE_CL_ILLUMINATION				"cl_illumination"
# define RT_SOURCE_CL_SAMPLE_STORE				"cl_sample_store"
# define RT_SOURCE_CL_MAIN						"cl_main"

#endif
